"""Initial schema creation

Peek Plugin Database Migration Script

Revision ID: 42a2faadf6c9
Revises: 
Create Date: 2017-03-01 18:08:33.035242

"""

# revision identifiers, used by Alembic.
revision = '42a2faadf6c9'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uniqueId', sa.String(length=50), nullable=False),
    sa.Column('userId', sa.String(length=50), nullable=False),
    sa.Column('dateTime', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('iconPath', sa.String(length=200), nullable=True),
    sa.Column('routePath', sa.String(length=200), nullable=True),
    sa.Column('routeParamJson', sa.String(length=200), nullable=True),
    sa.Column('confirmedPayload', sa.String(length=10000), nullable=True),
    sa.Column('confirmType', sa.Integer(), server_default='0', nullable=False),
    sa.Column('state', sa.Integer(), server_default='0', nullable=False),
    sa.Column('notificationType', sa.Integer(), server_default='0', nullable=False),
    sa.Column('notificationsSent', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uniqueId'),
    schema='pl_active_task'
    )
    op.create_table('TaskAction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taskId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('confirmMessage', sa.String(length=200), nullable=True),
    sa.Column('actionedPayload', sa.String(length=10000), nullable=True),
    sa.ForeignKeyConstraint(['taskId'], ['pl_active_task.Task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pl_active_task'
    )
    op.create_index('idx_TaskAction_taskId', 'TaskAction', ['taskId'], unique=False, schema='pl_active_task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_TaskAction_taskId', table_name='TaskAction', schema='pl_active_task')
    op.drop_table('TaskAction', schema='pl_active_task')
    op.drop_table('Task', schema='pl_active_task')
    # ### end Alembic commands ###
