"""Initial table creation

Peek App Database Migration Script

Revision ID: 8d21137a2c61
Revises: 
Create Date: 2016-11-04 19:39:33.513670

"""

# revision identifiers, used by Alembic.
revision = '8d21137a2c61'
down_revision = None
branch_labels = None
depends_on = None

import sqlalchemy as sa

from alembic import op

schema = 'pl_active_task'

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ActiveTaskTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string1', sa.String(50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema=schema
    )
    op.create_index('idx_ActiveTaskTable_unique_index', 'ActiveTaskTable', ['id', 'string1'],
                    unique=True, schema=schema)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ActiveTaskTable_unique_index', table_name='ActiveTaskTable', schema=schema)
    op.drop_table('ActiveTaskTable', schema=schema)
    ### end Alembic commands ###
